# Generated by Django 5.0.14 on 2025-06-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern_type',
            name='description',
        ),
    ]
